class GoBoard{
  constructor(canvas){ this.canvas=canvas; this.ctx=canvas.getContext("2d"); this.size=19; this.board=[]; this.last=null; this.reset(19); }
  reset(size=19){ this.size=size; this.board=Array.from({length:size},()=>Array(size).fill(null)); this.last=null; this.draw(); }
  inside(x,y){return x>=0&&y>=0&&x<this.size&&y<this.size}
  setSetupBlack(points){ points.forEach(p=>{if(this.inside(p.x,p.y)) this.board[p.y][p.x]="B"}); this.draw(); }
  play(move){ if(move.pass){this.last=null; this.draw(); return} if(!this.inside(move.x,move.y)) return; this.board[move.y][move.x]=move.color; this.last={x:move.x,y:move.y,color:move.color}; this.capture(move.color==="B"?"W":"B"); this.draw(); }
  rebuild(setup,moves,upto){ this.reset(this.size); this.setSetupBlack(setup); for(let i=0;i<upto;i++) this.play(moves[i]); if(upto===0) this.draw(); }
  group(x,y,seen){ const color=this.board[y][x], stack=[[x,y]], stones=[], libs=new Set(); const key=(a,b)=>a+","+b; seen.add(key(x,y)); while(stack.length){ const [cx,cy]=stack.pop(); stones.push([cx,cy]); [[1,0],[-1,0],[0,1],[0,-1]].forEach(([dx,dy])=>{ const nx=cx+dx, ny=cy+dy; if(!this.inside(nx,ny)) return; const v=this.board[ny][nx]; if(v===null) libs.add(key(nx,ny)); else if(v===color && !seen.has(key(nx,ny))){ seen.add(key(nx,ny)); stack.push([nx,ny]); }});} return {stones, liberties:libs.size}; }
  capture(color){ const seen=new Set(); for(let y=0;y<this.size;y++){ for(let x=0;x<this.size;x++){ if(this.board[y][x]===color && !seen.has(x+","+y)){ const g=this.group(x,y,seen); if(g.liberties===0) g.stones.forEach(([sx,sy])=>this.board[sy][sx]=null); }}}}
  draw(){ const ctx=this.ctx,w=this.canvas.width,h=this.canvas.height; ctx.clearRect(0,0,w,h); const wood=ctx.createLinearGradient(0,0,w,h); wood.addColorStop(0,"#efc57d"); wood.addColorStop(.5,"#ca9147"); wood.addColorStop(1,"#f1ca85"); ctx.fillStyle=wood; ctx.fillRect(0,0,w,h); const margin=w*0.07, cell=(w-margin*2)/(this.size-1); this.margin=margin; this.cell=cell; ctx.strokeStyle="#2b1a0a"; ctx.lineWidth=2; for(let i=0;i<this.size;i++){ const p=margin+i*cell; ctx.beginPath(); ctx.moveTo(margin,p); ctx.lineTo(w-margin,p); ctx.stroke(); ctx.beginPath(); ctx.moveTo(p,margin); ctx.lineTo(p,h-margin); ctx.stroke(); } if(this.size===19){ ctx.fillStyle="#2b1a0a"; [3,9,15].forEach(y=>[3,9,15].forEach(x=>{ ctx.beginPath(); ctx.arc(margin+x*cell,margin+y*cell,5.5,0,Math.PI*2); ctx.fill(); })); } for(let y=0;y<this.size;y++){ for(let x=0;x<this.size;x++){ if(this.board[y][x]) this.stone(x,y,this.board[y][x]); }} if(this.last) this.marker(this.last.x,this.last.y); }
  stone(x,y,color){ const ctx=this.ctx,cx=this.margin+x*this.cell,cy=this.margin+y*this.cell,r=this.cell*.43; const g=ctx.createRadialGradient(cx-r*.35,cy-r*.35,r*.1,cx,cy,r); if(color==="B"){ g.addColorStop(0,"#666"); g.addColorStop(.45,"#111"); g.addColorStop(1,"#000"); ctx.strokeStyle="#000"; }else{ g.addColorStop(0,"#fff"); g.addColorStop(.65,"#eee"); g.addColorStop(1,"#bbb"); ctx.strokeStyle="#777"; } ctx.fillStyle=g; ctx.beginPath(); ctx.arc(cx,cy,r,0,Math.PI*2); ctx.fill(); ctx.stroke(); }
  marker(x,y){ const ctx=this.ctx,cx=this.margin+x*this.cell,cy=this.margin+y*this.cell,s=this.cell*.22; ctx.fillStyle="#d40000"; ctx.beginPath(); ctx.moveTo(cx,cy-s); ctx.lineTo(cx-s,cy+s*.8); ctx.lineTo(cx+s,cy+s*.8); ctx.closePath(); ctx.fill(); }
}
