const defaultStocks=[{code:'0050',name:'元大台灣50',price:198.5,score:82},{code:'0056',name:'高股息',price:37.8,score:70},{code:'006208',name:'富邦台50',price:116.2,score:84},{code:'2330',name:'台積電',price:1035,score:78},{code:'2317',name:'鴻海',price:214,score:73}];
let stocks=JSON.parse(localStorage.getItem('stocksV3')||'null')||defaultStocks;let selected=stocks[2];
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('stocksV3',JSON.stringify(stocks))}
function renderWatch(){ $('watchList').innerHTML=''; stocks.forEach(s=>{const d=document.createElement('div');d.className='stock '+(selected.code===s.code?'active':'');d.innerHTML=`<div class="code">${s.code}</div><div class="name">${s.name}｜示範現價 ${s.price}</div>`;d.onclick=()=>{selected=s;renderAll()};$('watchList').appendChild(d)})}
function renderAI(){ $('selectedStock').textContent=`${selected.code} ${selected.name}`; const level=selected.score>=80?'偏多，可分批布局':selected.score>=72?'中性偏多，等待回檔':'觀望，控制風險'; $('aiText').innerHTML=`AI 強弱分數：<b>${selected.score}</b><br>趨勢判斷：${level}<br>策略：分批、停損 3%～5%、停利 8%～12%。`; $('signal').textContent=selected.score>=80?'買進觀察':selected.score>=72?'持有觀察':'暫時觀望'}
function drawChart(){const c=$('chart'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<22;i++){let x=35+i*38;let y=210-Math.sin(i/2+selected.score/20)*55-i*3+(Math.random()*18); if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--blue');ctx.stroke();for(let i=0;i<18;i++){let x=45+i*46;let h=40+Math.random()*120;ctx.fillRect(x,310-h,18,h)}}
function renderAll(){renderWatch();renderAI();drawChart()}
$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('darkV3',document.body.classList.contains('dark'))}; if(localStorage.getItem('darkV3')==='true')document.body.classList.add('dark');
$('addBtn').onclick=()=>{let code=$('stockCode').value.trim(),name=$('stockName').value.trim()||'自訂股票';if(!code)return alert('請輸入股票代號');stocks.push({code,name,price:100,score:70});save();$('stockCode').value='';$('stockName').value='';renderAll()};
$('calcBtn').onclick=()=>{let cost=+$('cost').value,shares=+$('shares').value,price=+$('price').value;if(!cost||!shares||!price)return alert('請輸入完整資料');let p=(price-cost)*shares;let r=((price-cost)/cost*100).toFixed(2);$('profitResult').textContent=`損益：${p.toLocaleString()} 元，報酬率：${r}%`;$('profitResult').style.color=p>=0?'var(--green)':'var(--red)'};
$('tradeBtn').onclick=()=>{let row=document.createElement('tr');row.innerHTML=`<td>${$('tradeDate').value||new Date().toISOString().slice(0,10)}</td><td>${$('tradeCode').value||selected.code}</td><td>${$('tradeType').value}</td><td>${$('tradePrice').value}</td><td>${$('tradeShares').value}</td>`;$('tradeBody').prepend(row)};
renderAll();
