const initial=[['0050','元大台灣50'],['0056','高股息'],['006208','富邦台50'],['2330','台積電'],['2317','鴻海']];
let stocks=JSON.parse(localStorage.getItem('stocksV31')||'null')||initial;let selected=stocks[0][0];
const qs=id=>document.getElementById(id);
function save(){localStorage.setItem('stocksV31',JSON.stringify(stocks))}
function pseudo(code,base=100){let n=[...String(code)].reduce((a,c)=>a+c.charCodeAt(0),0);return +(base+(n%80)+(Math.sin(n)*8)).toFixed(2)}
function renderWatch(){qs('watchList').innerHTML='';stocks.forEach(([c,n])=>{let p=pseudo(c,40),chg=((p%7)-3).toFixed(2);let div=document.createElement('div');div.className='watch-item '+(c===selected?'active':'');div.innerHTML=`<div>${c}<small>${n}｜${p} 元｜<span class="${chg>=0?'positive':'negative'}">${chg>=0?'▲':'▼'} ${Math.abs(chg)}%</span></small></div><button class="del">刪</button>`;div.onclick=e=>{if(e.target.className==='del'){stocks=stocks.filter(s=>s[0]!==c);if(selected===c&&stocks[0])selected=stocks[0][0];save();renderAll();return}selected=c;renderAll()};qs('watchList').appendChild(div)})}
function analysis(){let stock=stocks.find(s=>s[0]===selected)||stocks[0];if(!stock)return;let p=pseudo(stock[0],50),rsi=Math.round(45+(p%35)),score=rsi>65?'★★★★★':rsi>55?'★★★★☆':'★★★☆☆',sig=rsi>68?'偏多，可分批布局':rsi>52?'觀望，等待突破':'保守，注意風險';qs('selectedStock').textContent=`${stock[0]} ${stock[1]}`;qs('score').textContent=score;qs('aiText').innerHTML=`趨勢分數：${rsi} 分。<br>建議：${sig}。<br>停損參考：-3%～-5%；停利參考：+8%～+12%。`;qs('signal').textContent=sig;qs('rsi').textContent=`RSI：${rsi}`;qs('kd').textContent=`KD：${rsi>60?'黃金交叉':'整理'}`;qs('macd').textContent=`MACD：${rsi>58?'翻紅':'等待'}`;qs('ma').textContent=`MA20：${rsi>55?'向上':'持平'}`;drawChart(stock[0])}
function drawChart(code){let cvs=qs('chart'),ctx=cvs.getContext('2d'),w=cvs.width,h=cvs.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#dbe3ef';ctx.lineWidth=1;for(let i=1;i<6;i++){ctx.beginPath();ctx.moveTo(40,i*h/6);ctx.lineTo(w-20,i*h/6);ctx.stroke()}let seed=[...String(code)].reduce((a,c)=>a+c.charCodeAt(0),0),x=50,last=180;for(let i=0;i<38;i++){let open=last+(Math.sin(seed+i)*16),close=open+(Math.cos(seed*i+3)*22),high=Math.max(open,close)+12,low=Math.min(open,close)-12;let y=v=>h-40-(v-100)*1.25;ctx.strokeStyle=close>=open?'#16a34a':'#dc2626';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y(high));ctx.lineTo(x,y(low));ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(x-6,Math.min(y(open),y(close)),12,Math.max(4,Math.abs(y(open)-y(close))));last=close;x+=22}ctx.strokeStyle='#4169e1';ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<38;i++){let yy=160+Math.sin(i/4+seed)*38+i*0.6,xx=50+i*22;if(i===0)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}ctx.stroke()}
function renderAll(){renderWatch();analysis()}
qs('addBtn').onclick=()=>{let c=qs('stockCode').value.trim(),n=qs('stockName').value.trim()||'自選股';if(!c)return;stocks.push([c,n]);selected=c;save();qs('stockCode').value='';qs('stockName').value='';renderAll()};
qs('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('darkV31',document.body.classList.contains('dark'))};if(localStorage.getItem('darkV31')==='true')document.body.classList.add('dark');
qs('calcBtn').onclick=()=>{let cost=+qs('cost').value,shares=+qs('shares').value,price=+qs('price').value;if(!cost||!shares||!price)return;let pl=(price-cost)*shares,rate=(price-cost)/cost*100;qs('profitResult').innerHTML=`損益：<b class="${pl>=0?'positive':'negative'}">${pl.toFixed(0)} 元（${rate.toFixed(2)}%）</b>｜市值：${(price*shares).toFixed(0)} 元`};
qs('tradeDate').value=new Date().toISOString().slice(0,10);qs('tradeBtn').onclick=()=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${qs('tradeDate').value}</td><td>${qs('tradeCode').value}</td><td>${qs('tradeType').value}</td><td>${qs('tradePrice').value}</td><td>${qs('tradeShares').value}</td>`;qs('tradeBody').prepend(tr)};
qs('refreshBtn').onclick=()=>{let v=23800+Math.random()*350,chg=(Math.random()*260-80);qs('marketIndex').textContent=v.toFixed(2);qs('marketChange').textContent=`${chg>=0?'▲':'▼'} ${Math.abs(chg).toFixed(2)}（${(chg/v*100).toFixed(2)}%）`;qs('marketChange').className=chg>=0?'up':'negative'};
renderAll();
